spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: hong
    password: 1111
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace