spring:
  config:
    import:
      - classpath:/yaml/application-dev.yml
      - classpath:/yaml/application-local.yml
      - classpath:/yaml/application-log.yml
  profiles:
    group:
      logging: dev, log
    active: logging
#    active: local